server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: test-route
          uri: http://localhost:8888
          predicates:
            - Path=/**

management:
  endpoints:
    web:
      exposure:
        include: "*"